### ISSUE TITLE
Some problems in my plugin 

### ISSUE THREAD

**Issue by ghost** [baudehlo/Haraka#593] opened 2014-05-26 12:19 UTC
I'm currently testing my Haraka plugin and I have some problems/errors. 

What I want to do is get every new mail in Haraka(using it as a smtp proxy), send it to a server to analyze it, and then send it to his destination(I'm currently using a postfix server)

I want to process a large number of emails and when I watch the log to observe every mail received , I see that the mails are somehow intercalated and I cant follow the mails log one at a time . For example :  
[DEBUG] [90B9646A-30AD-45D1-A111-42F81A8A14EA] [core] running connect hooks
[DEBUG] [0E563B4A-51F0-4481-90BB-2BE1E4C99798] [core] running connect hooks
[DEBUG] [424DC560-793A-4788-8C0C-6E6B9941C52D] [core] running ehlo hooks
[DEBUG] [424DC560-793A-4788-8C0C-6E6B9941C52D] [core] running capabilities hooks
[DEBUG] [90B9646A-30AD-45D1-A111-42F81A8A14EA] [core] running ehlo hooks
[DEBUG] [90B9646A-30AD-45D1-A111-42F81A8A14EA] [core] running capabilities hooks
[DEBUG] [0E563B4A-51F0-4481-90BB-2BE1E4C99798] [core] running ehlo hooks
[DEBUG] [0E563B4A-51F0-4481-90BB-2BE1E4C99798] [core] running capabilities hooks

Here are  2 connect hooks that are one after another and normally , I think, it should be just one connect hook ( of the mail received) and the second one should appear when the next mail comes. 

Also , in the log I see this errors : 

1. Plugin rcpt_to.disposable timed out on hook queue - make sure it calls the callback.
2. Error: too many connections from 10.100.whatever

Someone on IRC said that the second one could come from postfix(there is a limit for connections)  . I'll check it out ASAP.

The first one I have a feeling that comes from my rcpt_to.disposable plugin . I send the data to server using a http sync request . Is a long response from server affecting the email processing?

And another problem I just seen : when somebody is sending me many mails in short time(100 mails in 1 minute) , haraka seems to freeze . I dont receive the mails but after some time(which depends, 15-30 minutes or after restarting haraka ) it seems to get back to normal .

**Comment by celesteking** [comment] 2015-03-31 11:36
I'd close this "bug" as it's not a bug but more of a support request.

**Comment by smfreegard** [comment] 2015-03-31 12:06
Agreed

**Closed by smfreegard** 2015-03-31 12:06 UTC
